### ISSUE TITLE
Add `addExtension` analogue from `filepath`

### ISSUE THREAD

**Issue by ChShersh** [commercialhaskell/path#105]
Sometimes `setExtension` (or `(-<.>)` operator) is not enough. Especially when working with Haskell-like files:

```haskell
λ: hsFileName <- parseRelFile "Data.List"
λ: hsFileName 
"Data.List"
λ: setFileExtension ".symbols" hsFileName
"Data.symbols"  -- want to have Data.List.symbols here
```

I propose to add `addExtension` function similar to [one from `filepath` library](http://hackage.haskell.org/package/filepath-1.4.1.2/docs/System-FilePath-Posix.html#v:addExtension) with corresponding `(<.>)` operator. It may have next signature similar to `setExtension`:

```haskell
addExtension :: MonadThrow m
  => String            -- ^ Extension to add
  -> Path b File       -- ^ Old file name
  -> m (Path b File)   -- ^ New file name with the desired extension added at the end
```

**Comment by mrkkrp** [comment]
I'm in favor.

**Comment by NorfairKing** [comment]
Me too.

**Comment by joehillen** [comment]
I'm in favour of this as well.

@ChShersh would you be willing your write a PR for this?

**Comment by ChShersh** [comment]
@joehillen I don't mind implementing this addition as a PR. Will do this relatively soon.
