### ISSUE TITLE
resolveDir is present in docs, but missing from the library

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/path#107]
In this documentation:
https://github.com/commercialhaskell/path

you'll find
```haskell
resolveDir :: (MonadIO m, MonadThrow m)
           => Path Abs Dir -> FilePath -> m (Path Abs Dir)
```
but it's missing from the library.

**Comment by mrkkrp** [comment]
It's here: https://www.stackage.org/haddock/nightly-2017-07-31/path-io-1.3.3/Path-IO.html#v:resolveDir

**Comment by varosi** [comment]
Thanks a lot! I have just found it, but didn't know that it's in a separate package.
