### ISSUE TITLE
Expose splitExtension API

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/path#121]
#115 introduced the `splitExtension` API but that PR did not expose it. We need to decide what the signature should be. One point that I was thinking about `splitExtension` and `fileExtension` APIs is whether they should throw instead of returning an empty string when there is no extension present. 

The annoying thing is that we do not accept an empty string as a valid extension when setting an extension using `addFileExtension` and `setFileExtension` however we return it as output of `fileExtension`. If we throw (which is equivalent to returning a `Maybe`) in that case then it will be explicit and laws like this will hold at runtime:

```
let (f, ext) = splitExtension file in addFileExtension ext f == file
```

**Comment by sjakobi** [comment]
Looks like this was resolved in #122.
