### ISSUE TITLE
Reduce normalization overhead by requiring filepath >= 1.4

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#127]
The latest fixes to `System.FilePath.normalise` were in `filepath-1.4.0.0` which was bundled with GHC-7.10. I suspect that we could kill quite a bit of the normalization overhead if we could rely on `filepath >= 1.4` and delete some of our normalization code.

**Comment by NorfairKing** [comment]
@sjakobi this sounds good to me! Can we either do it or close this?
