### ISSUE TITLE
Parsing of current directory path (".") is still platform-dependent

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#129]
Here's a demonstration on Linux:

```
λ Path x = [Path.Posix.reldir|.|]
λ x
""
λ Path x = [Path.Windows.reldir|.|]
λ x
".\\"
```

The root cause of the problem is that our definition of `relRootFP` uses the platform-dependent `System.FilePath.pathSeparator`:

https://github.com/commercialhaskell/path/blob/8f9354d32b80f669cfa0a76e6522be1e3e21c638/src/Path/Internal.hs#L56-L58

A fix should probably move `relRootFP` into `Path.Include`.

**Comment by Martinsos** [comment]
I believe this is fixed with #163?

**Comment by sjakobi** [comment]
> I believe this is fixed with #163?

I don't see any library changes in #163. Did you mean a different PR?

**Comment by Martinsos** [comment]
Sorry, my mistake! #167 it is.

**Comment by sjakobi** [comment]
Neat! Thanks a lot for the fix, @Martinsos! :)
