### ISSUE TITLE
Export `valid*` functions

### ISSUE THREAD

**Issue by rkoeninger** [commercialhaskell/path#133]
While working on #74 (PR #128), I saw that there are instances for `Validity` that duplicate some logic in unexported functions in Include.hs:

https://github.com/commercialhaskell/path/blob/d4e16f96bebb06ae1f3e645aaeabc550bd290515/test/Path/Gen.hs#L21-L27

https://github.com/commercialhaskell/path/blob/d4e16f96bebb06ae1f3e645aaeabc550bd290515/src/Path/Include.hs#L643-L648

Should there be exported functions to determine path validity (4 of them)?

They would be used by the test suite.

In #69, the `System.FilePath.isValid` function is discussed and this library doesn't have and validity checking functions. I guess you could try to use one of the functions in `path` and see if it throws? The fact that so much validation logic is in the test suite makes me feel like it would be useful in general. And Unix/Windows-specific validity could be established as well.

**Comment by sjakobi** [comment]
I'd appreciate the addition of `valid{Abs,Rel}{File,Dir}`!

**Comment by rkoeninger** [comment]
I'll start a PR, and if merged, I'll use the `valid*` functions in my other PR to fix the validity tests.

**Comment by rkoeninger** [comment]
@sjakobi Should there be 4 functions, one for each combo of `Abs|Rel`, `Dir|File`, or should there be 4 instances of an `isValid` function using typeclasses?

**Comment by sjakobi** [comment]
> I'll start a PR, and if merged, I'll use the `valid*` functions in my other PR to fix the validity tests.

Great! :)

> Should there be 4 functions, one for each combo of Abs|Rel, Dir|File, or should there 1 overloaded valid function using 4 instances of a typeclass?

I think having 4 separate functions has more precedents with the `parse*`, `from*` and `abs*` functions. 

A typeclass approach would likely require some discussion among the maintainers – something which I'm not too keen on…

**Comment by NorfairKing** [comment]
> The fact that so much validation logic is in the test suite makes me feel like it would be useful in general.

I completely agree with this sentiment, but instead of creating four new functions, we can just move these instances to the library, and we'd be done!

**Comment by rkoeninger** [comment]
There's another issue with creating general `Validity` instances - what exactly are the criteria for validity?

On my working branch, I have 2 groups of functions:

  * `isValid*` that check if a path will be successfully parsed by the `parse*` functions (e.g. directory paths don't require trailing slashes)
  * `isNormalized*` that match the `Validity` instances in the test suite (e.g. directory paths require trailing slashes)

Do we need both? Were the `parse*` functions not particular enough?

**Comment by sjakobi** [comment]
> what exactly are the criteria for validity?

IMHO it should simply be

```
validXY p = parseXY (toFilePath p) == Just p
```

**Comment by NorfairKing** [comment]
> Sure. No matter where we keep the validation logic, we won't be able to test it with itself.

This is not a trivial thing though.
There is a semantic difference between parsing something with a valid result, and checking if the result is valid.

That is, unless you use something like `constructValid . Path`.

**Comment by rkoeninger** [comment]
@sjakobi  @NorfairKing  Added PR for what i have so far: #134
