### ISSUE TITLE
Thoughts on adding an IsString instance for Path

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/path#135]
In lieu of using quasiquoters (which are a little hard to read because my syntax highlighting doesn't cover quasiquotes), it would be great if we could add IsString instances for Path. What I currently have in my code base is:

```
instance IsString (Path Abs File) where
  fromString = fromJust . parseAbsFile

-- etc.
```

Most of the time, the type is inferred fine

```
specialDir :: Path Rel Dir
specialDir = "foo/"

specialFile :: Path Rel File
specialFile = specialDir </> "bar.txt"
```

And in cases where it's not, you still have the ability to use quasiquoters. Are there any downsides to this?

**Comment by NorfairKing** [comment]
> Are there any downsides to this?

https://github.com/commercialhaskell/path#overloaded-strings

**Comment by brandon-leapyear** [comment]
ah I do remember seeing that a while ago. Cool.
