### ISSUE TITLE
add a Read instance

### ISSUE THREAD

**Issue by andrewufrank** [commercialhaskell/path#139]
I like and use `Path` a lot but observe a problem for regression testing. In a regression test for some complex functionality I use input of complex data types which are produced by `Show` of a results of a function and `Read` these results  to produce input for another function. `Path` not having a `Read` instance kills this approch often. 
The result type of `Read` is known and the value was produced from `Show` of a valid path, thus I do not see an issue with type safety. 
Could this be achieved? At the moment I use an ugly wrapper around`Path` and  I would love to get rid of.
Thank you for a well thought out package!

**Comment by NorfairKing** [comment]
I don't see any obvious problems with adding a `Read` instance, but this:

> I use input of complex data types which are produced by Show of a results of a function and Read these results to produce input for another function. 

sounds like a _really_ bad idea.
I'm interested to hear what the other maintainers think.

**Comment by andrewufrank** [comment]
could you expand why you think this is a bad idea and what you would propose to improve regression testing for single, complex and IO using functions. Appreciate suggestions a lot!

**Comment by NorfairKing** [comment]
> could you expand why you think this is a bad idea and what you would propose to improve regression testing for single, complex and IO using functions. Appreciate suggestions a lot!

Absolutely, but it's independent of this PR. Send me an email and let's talk about it.
