### ISSUE TITLE
Binary instance

### ISSUE THREAD

**Issue by locallycompact** [commercialhaskell/path#158]
Hi, I'm trying to use Path in Shake oracle rules but shake expects a Binary instance for its Rule type. Has the binary instance been left out on purpose or can this be added?

**Comment by NorfairKing** [comment]
It's been left out so that there doesn't need to be a dependency on any particular serialisation library.
Which `Binary` are you talking about?

**Comment by locallycompact** [comment]
The one in this. https://hackage.haskell.org/package/shake-0.18.5/docs/Development-Shake-Classes.html

**Comment by NorfairKing** [comment]
> I assumed this was kid of a stock thing. 
It's not, but I once made the same assumption. Don't worry about it.
Feel free to close this issue if you think we're done here.
