### ISSUE TITLE
QuasiQuoters and TH smart constructors are broken

### ISSUE THREAD

**Issue by mmhat** [commercialhaskell/path#159]
Since the addition of `Lift` instances (commit [68314ea70b670f156975049505015ac94dd66557](https://github.com/commercialhaskell/path/commit/68314ea70b670f156975049505015ac94dd66557)) the following is possible:

    foo :: Path Abs Dir
    foo = [relfile|foo|]

Since the quasi quotes use the `mk{Abs,Rel}{Dir,File}` functions under the hood it applies to them, too.

This is IMHO clearly a bug.

**Comment by NorfairKing** [comment]
I don't understand why this happens, _at all_. Could you explain that a bit more?

**Comment by mmhat** [comment]
Before the commit I mentioned above `[relfile|foo|]` (or `$(mkRelFile "foo")`) spliced in `Path "foo" :: Path Rel File`. Now look at [this](https://github.com/commercialhaskell/path/commit/68314ea70b670f156975049505015ac94dd66557#diff-c8363c22356817d95126a6ad70c6ec80L574) line of the commit: The author removed the previous implementation and delegated the hard work to the `Lift` instance [here](https://github.com/commercialhaskell/path/commit/68314ea70b670f156975049505015ac94dd66557#diff-ef9ceb40627a283ccfd1da10f0782d17R110). But now the `:: Path Rel File` part is missing and hence the splice of the quasi-quoter and the underlying TH function is `Path "foo"` which is of type `Path b t`.

The big question IMHO is: How could this be merged unnoticed and even find it's way into the test suite? If you look at my pull request #160 you may note that I had to change parts of the Windows tests (e.g. [here](https://github.com/commercialhaskell/path/pull/160/commits/07373cb5c697c51e21638611de3ea3c866c23b84#diff-55fe0c8008794babb0a356f17d4f4a1eR84)) where the function `dirnamesShouldBeEqual :: Path b Dir ->  Path b Dir -> Bool` was applied to Paths with different bases without complaints.

I only noticed that bug when path-0.7.0 found its way into a recent Stackage snapshot and a whole lot of stuff didn't typecheck anymore because GHC wasn't able to figure out the concrete types for the path bases and path types.

Please let me know if this makes sense to you.

**Comment by mmhat** [comment]
@NorfairKing If you want to comprehend the issue yourself do the following:

1. Checkout the sources of path-0.6.1
2. In GHCi set the `-ddump-splices` option in order to see the code generated by the TH stuff.
3. Run the example above.

Now do the same with path-0.7.0. Note the differences.
Now do the same with the sources of my pull request. It should look like the one of path-0.6.1.

**Comment by NorfairKing** [comment]
I'm impressed with your digging, but I don't understand why this doesn't work:
https://github.com/commercialhaskell/path/commit/68314ea70b670f156975049505015ac94dd66557#diff-c8363c22356817d95126a6ad70c6ec80L570-R559
The parsing and `error`ing still happens right?

**Comment by NorfairKing** [comment]
Oh I think I understand the ambiguities that you talked about.
The parsing still happens at compile time (so I don't see how your example would still compile?) but the generated code has no type annotation.
Do I understand this right?

**Comment by mmhat** [comment]
Yes, that's it!

**Comment by NorfairKing** [comment]
OOOOH now I get it!
The parsing still happens correctly but you can assign it to the wrong type.
This is terrifying.
