### ISSUE TITLE
path-0.7.1 breaks a couple of stackages

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/path#161]
I noticed while working on latest Stackage Nightly that path-0.7.1 breaks building

- [ ] life-sync-1.1.0.0 (@chshersh @vrom911)
- [ ] hapistrano-0.4.0.1 (@stackbuilders)

Maybe it is an intentional change?
Anyway let me put a temporary Stackage upper-bound on path for now.

```
--  While building package life-sync-1.1.0.0 using:                                                                        [9/9255]
      /var/stackage/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-
linux/Cabal-3.0.1.0 build lib:life-sync exe:life test:life-sync-test --ghc-options ""
    Process exited with code: ExitFailure 1
    Logs have been written to: /var/stackage/work/unpack-dir/.stack-work/logs/life-sync-1.1.0.0.log

    Configuring life-sync-1.1.0.0...
    Preprocessing library for life-sync-1.1.0.0..
    Building library for life-sync-1.1.0.0..
    [ 8 of 12] Compiling Life.Main.Init
    
    /var/stackage/work/unpack-dir/unpacked/life-sync-1.1.0.0-648d723919acabd4d14283e17726ff7a04fbc1eaaf3d14a1fbaf53677a38bf80/src/L
ife/Main/Init.hs:34:15: error:
        • Not in scope: type constructor ‘Rel’
        • In the untyped splice: $(mkRelFile ".bash_profile")
       |
    34 |           [ $(mkRelFile ".bash_profile")
       |               ^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
    /var/stackage/work/unpack-dir/unpacked/hapistrano-0.4.0.1-6ce012f5ecc2306af2d35908025db4ddc16a2f386ce419dac3f7d0fa9e47e6c7/spec
/System/HapistranoConfigSpec.hs:24:72: error:
        • Not in scope: type constructor ‘Abs’
        • In the untyped splice: $(mkAbsDir "/")
       |
    24 |               { configSource = LocalDirectory { localDirectoryPath = $(mkAbsDir "/") } }
       |                                                                        ^^^^^^^^^^^^
```

**Comment by NorfairKing** [comment]
> Maybe it is an intentional change?

Yes. It looks like this code that got broken wasn't buggy, but it just didn't have enough imports.
The change was certainly intentional.

**Comment by vrom911** [comment]
`path-0.7.0` is working perfectly fine with `life-sync`. However, `path-0.7.1` fails with the error you mentioned. Which is weird as upgrading the minor bound should not lead to the breaking change, unless the `path` was released with the broken version. 
CHANGELOG doesn't help here as well. It doesn't mention any breaking changes. Could you please elaborate more on what is the migration guide for this version of `path`?

Should we just use `path < 0.7.1` as the latest version is not correctly released?

**Comment by NorfairKing** [comment]
We marked `0.7.1` as non-preferred and released `0.8.0` instead.

**Comment by chshersh** [comment]
@NorfairKing Thanks for releasing a major update! But the migration guide is still not clear from the changelog. Do you know, what needs to be done to make the code work with the new version?

**Comment by NorfairKing** [comment]
@chshersh You're right.
You need to make sure you have `Path` `Abs` `File` in scope if you use `[absfile|/something|]` because it will generate the equivalent of `Path something :: Path Abs File`.
