### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by Martinsos** [commercialhaskell/path#178]
I created (and we merged) https://github.com/commercialhaskell/path/pull/167 in order to solve bugs with inconsistent behaviour of Path.Posix and Path.Windows on different OSes.

I am author of https://github.com/wasp-lang/strong-path library and having these bugs fixed will allow me to remove the workaround I have in place right now in my code. However, there hasn't been a new release of Path for over a year -> is there a plan to have a new release soon, so I can update the version of Path I use in StrongPath and therefore get these bug fixes?

**Comment by NorfairKing** [comment]
@Martinsos Sounds like something I can do this weekend!

**Comment by NorfairKing** [comment]
https://hackage.haskell.org/package/path-0.9.0

Here you go :D

**Comment by Martinsos** [comment]
Happy news: I updated version of `path` in `strong-path` (https://github.com/wasp-lang/strong-path/pull/23) to new release and all bugs are now fixed :)! Yay

**Comment by NorfairKing** [comment]
> what do you do with Github Releases?

I mostly ignore them, they're not useful for libraries (IME), only for executables where you might want to update artefacts.


> I see that you have version tags for all the releases on Github, although you don't have for the latest one, 0.9.0. 

My mistake, fixed :)

> that is something you manually do when you release the new version?

Yes
