### ISSUE TITLE
Compatibility with hashable-1.4

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#182]
See https://hackage.haskell.org/package/hashable-1.4.0.0/changelog.

Could you upload a compatible release or revision? Thanks! :)

**Comment by bergmark** [comment]
ping, looks like just a bound bump is sufficient.

**Comment by NorfairKing** [comment]
Done. https://hackage.haskell.org/package/path-0.9.1
This will go into the release once we reach an LTS that contains this new hashable so that I can actually try it out.

**Comment by bergmark** [comment]
Thank you 🙇
