### ISSUE TITLE
Adding 'Data' instance to Rel, File, Abs and Dir

### ISSUE THREAD

**Issue by Martinsos** [commercialhaskell/path#186]
Is there are a particular reason why Rel, File, Abs and Dir are not deriving `Data`?

`data Path b t` is deriving Data, and what that does is create an instance Data for it where `b` and `t` also need to have instances of Data. However, since Rel, File, Abs and Dir don't have `Data` instances, this means that `Path Rel File`, `Path Rel Dir`, ... and so are not instances of `Data`.

I am encountering this is a problem now in https://github.com/wasp-lang/strong-path because I would like to make main type of StrongPath instance of `Data`, but the only thing stopping me from deriving `Data` is the fact that internally StrongPath uses `Path Rel File`, `Path Rel Dir` and so on, and those are not instances of `Data`.

I believe making `Rel`, `File` and similar instances of `Data` is as simple as just adding `Data` to `deriving`.

**Comment by NorfairKing** [comment]
Sounds agreeable!

**Comment by Martinsos** [comment]
> Sounds agreeable!

Ok! I created a very simple PR here https://github.com/commercialhaskell/path/pull/187 -> I think this should be it and I can see all the checks passing. Would love to get your eyes onto it also, just to make sure I haven't missed something.

**Comment by NorfairKing** [comment]
This is long-fixed. Just closing this issue now.

**Comment by NorfairKing** [comment]
This is long-fixed. Just closing this issue now.
