### ISSUE TITLE
Support `AbstractFilePath`

### ISSUE THREAD

**Issue by hasufell** [commercialhaskell/path#189]
## Motivation

The next filepath release will add support for a new API, which fixes subtle encoding issues and improves cross platform code and memory residence.

You can read about the state of the newly added API here: https://github.com/haskellfoundation/tech-proposals/issues/35

Release candidate with haddock is here: https://hackage.haskell.org/package/filepath-2.0.0.3/candidate

Demonstration about unsoundness of base with exotic encodings and how the new API fixes them is here: https://gist.github.com/hasufell/c600d318bdbe010a7841cc351c835f92

## Migrations

Migrations can happen once the `filepath`, `unix` and `Win32` packages are updated and in sync. A migration would usually involve using the new types from [System.AbstractFilePath](https://hackage.haskell.org/package/filepath-2.0.0.3/candidate/docs/System-AbstractFilePath.html) and the new API variants from [unix](https://github.com/haskell/unix/pull/202)/[Win32](https://github.com/haskell/win32/pull/198).

When writing low-level cross platform code manually (shouldn't generally be necessary), the usual strategy is this:

```hs
#if defined(mingw32_HOST_OS) || defined(__MINGW32__)
import qualified System.AbstractFilePath.Data.ByteString.Short.Word16 as SBS
import qualified System.AbstractFilePath.Windows as PFP
#else
import qualified System.AbstractFilePath.Data.ByteString.Short as SBS
import qualified System.AbstractFilePath.Posix as PFP
#endif

crossPlatformFunction :: AbstractFilePath -> IO ()
#if defined(mingw32_HOST_OS) || defined(__MINGW32__)
crossPlatformFunction (OsString pfp@(WS ba)) = do
    -- use filepath functions for windows specific operating system strings
    let ext = PFP.takeExtension pfp
    -- operate directly on the underlying bytestring (which is a wide character bytestring, so uses Word16)
    let foo = SBS.takeWhile
    ...
#else
crossPlatformFunction (OsString pfp@(PS ba)) = do
    -- use filepath functions for posix specific operating system strings
    let ext = PFP.takeExtension pfp
    -- operate directly on the underlying bytestring (which is just Word8 bytestring)
    let foo = SBS.takeWhile
    ...
#endif
```

Platform specific code can be written using [`PosixFilePath`](https://hackage.haskell.org/package/filepath-2.0.0.3/candidate/docs/System-AbstractFilePath-Posix.html)/[`WindowsFilePath`](https://hackage.haskell.org/package/filepath-2.0.0.3/candidate/docs/System-AbstractFilePath-Windows.html) types.

If you have further questions, please let me know. I'm going to write a blog post outlining the affairs and more in-depth intro and migration strategies close after the release. This is a heads up.

**Comment by mpilgrem** [comment]
@NorfairKing, I thought I might have a stab at implementing this but before I embarked on it (if I succeed) would it be welcomed?

**Comment by hasufell** [comment]
The blog post explaining migration is here: https://hasufell.github.io/posts/2022-06-29-fixing-haskell-filepaths.html

**Comment by mpilgrem** [comment]
@hasufell, on migration, can I pick your brains on something? Stack currently has types like this one:
~~~haskell
newtype BuildCache = BuildCache
    { buildCacheTimes :: Map FilePath FileCacheInfo
      -- ^ Modification times of files.
    }
    deriving (Generic, Eq, Show, Typeable, ToJSON, FromJSON)
~~~

and the `aeson` package has, as an instance of `FromJSON`:
~~~haskell
(FromJSONKey k, Ord k, FromJSON v) => FromJSON (Map k v)
~~~

but (a) the instances for `OsString` in `filepath` are limited to `Monoid`, `Semigroup`, `Generic`, `Show`, `NFData`, `Eq`, `Ord`, `Lift` and `Type`; and (b) the `aseon` package does not provide instances for `OsString`. I am not sure what is the way forward. Is there some 'recommended source' of orphan instances, somewhere?

**Comment by hasufell** [comment]
JSON instance is one of those few cases where **maybe** `String` is a better filepath since it's "normalized".

I mean, if you send the raw bytes from a machine with encoding CP932 to a machine with encoding UTF-8... what result are you expecting? Even worse, if you send `OsPath` from windows to a linux machine, it'll be utter garbage.

But if it's converted to a list of unicode codepoints, you can encode them into whatever you want and don't need to know the original encoding. It's the "unified" representation (but it's not lossless).

Whether the filepath makes sense on "the other end" is still up to interpretation.

If the aeson instance is for local use only, you could write an instance for OsPath and convert to base64, see https://github.com/haskell/aeson/issues/187

**Comment by hasufell** [comment]
Oh, and, given the "over the wire" scenario, you can turn the filepath back into an OsPath via [encodeFS](https://hackage.haskell.org/package/filepath-1.4.100.3/docs/System-OsPath.html#v:encodeFS).

This way you're possibly translating between different encodings and the semantics are "visible unicode characters", so to speak. That may not always be the semantics you want (e.g. for filepath whitelists you probably want the raw bytes).

**Comment by NorfairKing** [comment]
Done as of `0.9.6`.

**Comment by hasufell** [comment]
@mmhat I believe the next step would be adjusting https://hackage.haskell.org/package/path-io?

**Comment by mmhat** [comment]
> @mmhat I believe the next step would be adjusting https://hackage.haskell.org/package/path-io?

@hasufell Yes indeed! My general plan(s) regarding the `os-string`/`OsPath` stuff is (no particular order):

- Add support for `System.OsPath` to `path-io`.
- Finish and release https://github.com/mmhat/os-string-aeson
- Use that to create a new `path-aeson` package providing aeson instance for the `OsPath` paths.
- Resolve https://github.com/haskell/process/issues/252

**Comment by mpilgrem** [comment]
@mmhat, I am interested in your general plan and its goals. What is the current state of play?

**Comment by NorfairKing** [comment]
I'm guessing @mrkkrp would be the next person to ping :D
