### ISSUE TITLE
Random test suite failures

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#37]
I see random failures in several test cases when running `stack test` at c9e3aae8c0e8adb50ded50f4a20e805ea7910832:

```
  test/Main.hs:133: 
  1) Operations: stripDir produces a valid path on when passed a valid absolute file paths
       predicate failed on: Just "/\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m" (after 30 tests): 
       "/"
       "//\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m"

Randomized with seed 1063046505
```

```
  test/Main.hs:218: 
  1) Parsing: Path Rel Dir Produces valid paths when it succeeds
       predicate failed on: "\197ecUxJkrRm'6I\ACK\SUB..\SI\203\204\129'\146wS\209\135t\205Y\DELUlb\245\242A\203`\239p\247(\219l\197*w\ESC\171\211\238\&8}\a\192\210&9/" (after 75 tests): 
       "\197ecUxJkrRm'6I\ACK\SUB..\SI\203\204\129'\146wS\209\135t\205Y\DELUlb\245\242A\203`\239p\247(\219l\197*w\ESC\171\211\238\&8}\a\192\210&9"

  test/Main.hs:267: 
  2) Parsing: Path Rel File Produces valid paths when it succeeds
       predicate failed on: "\197ecUxJkrRm'6I\ACK\SUB..\SI\203\204\129'\146wS\209\135t\205Y\DELUlb\245\242A\203`\239p\247(\219l\197*w\ESC\171\211\238\&8}\a\192\210&9" (after 75 tests): 
       "\197ecUxJkrRm'6I\ACK\SUB..\SI\203\204\129'\146wS\209\135t\205Y\DELUlb\245\242A\203`\239p\247(\219l\197*w\ESC\171\211\238\&8}\a\192\210&9"

Randomized with seed 860936673
```

```
  test/Main.hs:136: 
  1) Operations: stripDir produces a valid path on when passed a valid absolute directory paths
       predicate failed on: Just "/" (after 20 tests): 
       "/"
       "//"

Randomized with seed 529729740
```

**Comment by chrisdone** [comment]
What does this produce on your machine?

``` haskell
bash-3.2$ stack ghci --test
> import Data.Validity
> fmap isValid (stripDir $(mkAbsDir "/") $(mkAbsFile "//\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m"))
True
> 
```

**Comment by sjakobi** [comment]
```
λ> import Data.Validity 
λ> :set -XTemplateHaskell 
λ> fmap isValid (stripDir $(mkAbsDir "/") $(mkAbsFile "//\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m"))
True
λ> stripDir $(mkAbsDir "/") $(mkAbsFile "//\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m")
"\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m"
λ> $(mkAbsFile "//\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m")
"/\172\160'\250\240bJ\f\235\148|\ENQ~>;=%w\238\DEL\206\174m"
```

**Comment by chrisdone** [comment]
That's quite curious. I'm not sure why the test fails. @NorfairKing Any idea?

**Comment by NorfairKing** [comment]
I do know why this fails. I said so in my pr: #36 

> I found a false positive because the validity instance is not strict enough yet. Stil WIP, but would like to hear your thoughts.

The validity instance is not strict enough because `Path "//"` is still considered a valid `Path Abs Dir`.
This may not be a problem in practice because "//" will be normalized to "/" upon parsing, but it should be reflected in the validity instance nonetheless.

**Comment by chrisdone** [comment]
Ohh; so the validity instance just needs to be stricter. We can probably replace the method implementations with just calling the parser and seeing if the resulting String matches the input.

**Comment by NorfairKing** [comment]
> We can probably replace the method implementations with just calling the parser and seeing if the resulting String matches the input.

Cool! Please mention me on that change. I can try doing it too, if you want.

**Comment by chrisdone** [comment]
Please give it a shot, you can put the Gen instances in .Internal along with the parsers if you need to.

**Comment by NorfairKing** [comment]
I made the validity instance more restrictive, see [here](https://github.com/NorfairKing/path/commit/d6d02aa54c284d5873b7af64e234eca01acf3054).
Now the validity instance is strict enough to expose some bugs:

```
$(mkAbsFile "/.") -- DANGEROUS
"/"
$(mkRelFile "a/.") -- Disobeys invariant: file does not end in slash
"a/"
$(mkRelFile "a..") -- Disobeys invariant: no double dot in filepath
"a.."
$(mkRelDir "a../") -- Disobeys invariant: no double dot in filepath
"a../"
```

We should add regressions tests for these when we fix them.

**Comment by sjakobi** [comment]
[Seems like](https://github.com/commercialhaskell/path/pull/73#issuecomment-284553256) #72 didn't fix this after all:

```
  test/ValidityTest.hs:149: 
  1) Parsing: Path Rel Dir Produces valid paths when it succeeds
       predicate failed on: "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_/" (after 81 tests): 
       "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_"

  test/ValidityTest.hs:161: 
  2) Parsing: Path Rel File Produces valid paths when it succeeds
       predicate failed on: "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_" (after 81 tests): 
       "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_"

Randomized with seed 173166278
```

I'll try to increase the depth so we at least get consistent failures. We also really need some shrinking there.

**Comment by sjakobi** [comment]
Hrm, `--qc-max-success 1000` still succeeds. Looks like we'll need to use that specific seed.

**Comment by sjakobi** [comment]
@NorfairKing: Why is `$(mkRelDir "a../")` an invalid path? I'd think that `..` is only problematic when it's an entire path segment like in `a/../`?

**Comment by NorfairKing** [comment]
> Why is $(mkRelDir "a../") an invalid path?

It's not, but the documentation says that it is.

**Comment by sjakobi** [comment]
> It's not, but the documentation says that it is.

Well it's invalid according to `Path.Gen.isValid`… I'll make a PR to fix that.

**Comment by NorfairKing** [comment]
How about we move the validity and genvalidity instances to the right place first?

**Comment by sjakobi** [comment]
> How about we move the validity and genvalidity instances to the right place first?

Please do that. Do you need any help with it? To me the priority is that the testsuites work and don't produce any false positives (or negatives?! IDK).

**Comment by sjakobi** [comment]
Is my understanding correct that we are going to continue seeing these random failures until in all the `Validity` instances we essentially have `isValid p@(Path fp) = parse fp == Just p`?

So, what actually needs to be done is to make the parsing functions more strict or alternatively clarify the parsing/validity semantics?

**Comment by NorfairKing** [comment]
> Please do that. Do you need any help with it?
Can't do it sooner than thursday. Moving between countries atm.

On your other question: I wouldn't make that claim.

**Comment by sjakobi** [comment]
No worries, we aren't in a hurry!

Good luck with the moving! :+1:

**Comment by sjakobi** [comment]
Optimistically closing this again since https://github.com/commercialhaskell/path/pull/78 has been merged.

Failures in validity-test on Windows are tracked in https://github.com/commercialhaskell/path/issues/74.
