### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/path#60]
Hi all,

After posting a [request for maintainers](https://mail.haskell.org/pipermail/haskell-cafe/2017-February/126401.html), the following people have expressed interest in being a comaintainer of the `path` package. I've added them as collaborators, and I've moved `path` under `commercialhaskell`.

* Simon Jakobi @sjakobi
* Tom Sydney Kerckhove @NorfairKing
* Wojciech Daniło @wdanilo
* Joe Hillenbrand @joehillen

Please include your Hackage usernames to be added to the Hackage maintainer list!

I'd like to remind us of the goals of this package:

> 1. Be simple, with simple types. 2. Prevent unexpected results and promote reasoning, disallowing certain inputs in order to achieve that. There should be only one way to represent a path once you have a `Path`. We don't compromise safety for the sake of convenience. There are other path libraries for that. 

That's all. I trust you guys can make the more straight-forward changes you need directly now, and for the bigger breaking changes the usual PR with some grace period for discussion and then merging will probably work fine? Thanks everyone for using and contributing! :+1: 😄 

Feel free to add yourself as a maintainer in the .cabal file.

I'll close this issue when everyone has hackage access.

**Comment by sjakobi** [comment]
That's a lot of (co)maintainers for such a small package! :grin: I'm sure we'll make this package even better than it already is!

I'm sjakobi on Hackage.

**Comment by chrisdone** [comment]
@sjakobi added!

**Comment by wdanilo** [comment]
I totally agree with the guidelines. Simon I think the number of
maintainers is not too big. It's much better to have a strong group of
maintainers seeing different perspectives and having different use cases in
mind than small group that don't really have much time to progress with the
library (parsec is an example of the later). Although path management seems
simple on the first look, there are many cases yet to be included to make
it a "standard", type safe Haskell path management Lib with simple end-user
experience.

My hackage name is "danilo2".

Thanks! :)
Wojciech Danilo

**Comment by chrisdone** [comment]
Added danilo2!

**Comment by mrkkrp** [comment]
I'm glad `path` has got more maintainers, this is a useful package that will benefit from more attention.  I'd propose myself as a co-maintainer, but I don't read Haskell Care these days, so I didn't know anything about this :-)

**Comment by sjakobi** [comment]
> I'd propose myself as a co-maintainer

Personally I think this is a great idea, especially because your [`path-io`](https://github.com/mrkkrp/path-io) is probably the most exhaustive consumer of our API.

**Comment by sjakobi** [comment]
I've made a Hackage revision to update the repository info – turns out GitHub also redirects from the old repo URL… :/

**Comment by chrisdone** [comment]
Agreed, I'll add @mrkkrp.

**Comment by NorfairKing** [comment]
Hithere. 
I'm really excited to be able to help here.
My hackage username is NorfairKing.

**Comment by chrisdone** [comment]
Added!

**Comment by mrkkrp** [comment]
Do you have a plan for what version to release next: 0.5.13 or 0.6.0? We could start assigning milestones to issues. For example things like #18 could be assigned to 0.6.0 as they require breaking changes.

**Comment by joehillen** [comment]
@mrkkrp Let's get some PRs open and then decide how to release them

**Comment by mrkkrp** [comment]
@chrisdone I've just read your post on Haskell Cafe. I recommend you buy this thing:

https://www.amazon.com/gp/product/B01KBKFT7C/

And switch to Dvorak (if you still type QWERTY). It's a bit pricy for a keyboard but if you suffer from RSI it will enable you to type again, and that's worth it. I have two of them!

**Comment by sjakobi** [comment]
Looks like we're off to a good start! :+1:

**Comment by sjakobi** [comment]
@chrisdone I just re-read the goals of this package and I don't really understand what the following sentence means. Can you elaborate what you meant by this?

> There should be only one way to represent a path once you have a Path.

**Comment by chrisdone** [comment]
I mean that you can't have a value foo/ or foo//. It's just foo/. Otherwise
we break equational reasoning or otherwise lead to normalization in
operations, whereas normalisation during creation leads to much simpler
operations, I think.
