### ISSUE TITLE
Setup AppVeyor 

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#61]
In progress at https://ci.appveyor.com/project/sjakobi/path.

**Comment by sjakobi** [comment]
@chrisdone: I believe that because I'm not an owner of the commercialhaskell organization, AppVeyor can't automatically add the appropriate webhooks in this repo.

As you are an owner of the organization you could do that by opening a (free) AppVeyor account and adding this project. Alternatively you could create an AppVeyor account for the entire commercialhaskell organization but I'm not quite sure what benefits that would bring.

**Comment by sjakobi** [comment]
Instruction for setting up an organizational account are in the paragraphs below https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization.

**Comment by chrisdone** [comment]
@sjakobi Started a build here: https://ci.appveyor.com/project/chrisdone/path

**Comment by sjakobi** [comment]
> @sjakobi Started a build here: https://ci.appveyor.com/project/chrisdone/path

Great! The webhooks seem to work alright!
