### ISSUE TITLE
Add benchmarks and look for optimizations

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#63]
I'm under the impression that parsing a `Path` has by and by become more expensive.

In https://github.com/commercialhaskell/stack/issues/1235#issuecomment-250891401 we discovered that `stack` was spending a very significant amount of time by parsing `Path`s in some workflows.

It would be nice if we could find some ways to make `path` a bit faster again. Right now I'm mostly thinking of redundant checks there.

**Comment by mrkkrp** [comment]
@sjakobi Do you indend to write the benchmarks? If yes, we should start assign people to issues so we know who does what.

**Comment by sjakobi** [comment]
> Do you indend to write the benchmarks?

I probably won't get around to it in the next few weeks. If anyone's interested, please assign the issue to yourself.

**Comment by NorfairKing** [comment]
+1 would like to see these benchmarks.

**Comment by sjakobi** [comment]
Once we have a better idea of the performance characteristics of path we could also consider switching to a different internal representation of filepaths. I'm thinking of `ByteString`, `Vector Char`, `Text` or maybe even foundation's `String`.

**Comment by mrkkrp** [comment]
This may be a bad idea given that all the consumers of `Path`s are taking `FilePath` and we are building `Path` from `FilePath`s too, which are `String`s. Converting back and forth will be much solwer and nastier, IMO. I think Chris once already said the same thing to someone who proposed something like this.

**Comment by NorfairKing** [comment]
Given that unix filepaths are just null-terminated byte arrays, converting to `bytestring` is probably not a bad idea, but only if `path-io` can avoid the intermediate `[Char]` too.

**Comment by mrkkrp** [comment]
`path-io` wraps functions from other packages that work with `Strings`.

**Comment by sjakobi** [comment]
Let's see the performance data before making a decision.

**Comment by sjakobi** [comment]
[One idea](https://github.com/haskell/filepath/issues/58#issuecomment-284542835) for optimizing `System.FilePath.isValid` from ndmitchell:

> Entirely possible - I imagine you could write a fold over the list as a state machine that would be way more efficient. Personally I'd probably QuickCheck it against filepath but reimplement from scratch.

**Comment by NorfairKing** [comment]
> path-io wraps functions from other packages that work with Strings.

Yes, but it's opaque, so we could replace the stuff under the hood.

> We can't help it, file paths are conventionally represented as Stringss right now in Haskell. I don't think we should fight this fact.

Maybe not yet, but this battle has to be faught at some point.

**Comment by NorfairKing** [comment]
It's been 7 years, people are still welcome to try though.
