### ISSUE TITLE
Add the 'isRoot' predicate

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/path#67]
This should return `True` when given path is root (upper level) directory.

**Comment by mrkkrp** [comment]
Depends on #18.

**Comment by sjakobi** [comment]
I'm surprised that I couldn't find an analogous function in either `filepath` or `directory`, indicating that maybe it isn't widely needed.

I'm not against adding it, but if it's added, I'd suggest adding it at some place where it doesn't distract from more useful functions.

**Comment by joehillen** [comment]
I feel like the problems described in #18 and #33 can be caught by expressing the special case for `/` at the type level rather than throw a runtime exception. I think this could be done in a fairly backwards compatible way. Give me a chance to test out the idea before merging anything.

**Comment by joehillen** [comment]
Nevermind, my idea wouldn't work without dependent types.

**Comment by sjakobi** [comment]
> I'm surprised that I couldn't find an analogous function in either filepath or directory, indicating that maybe it isn't widely needed.

I overlooked [`System.FilePath.isDrive`](http://hackage.haskell.org/package/filepath-1.4.1.2/docs/System-FilePath-Posix.html#v:isDrive) there. Not sure if we should also call our function `isDrive` then. It seems to me that calling Windows drives like `C:\\` a root is more common than calling the Posix root `/` a drive.

**Comment by NorfairKing** [comment]
PR welcome
