### ISSUE TITLE
Don't depend on the filepath version to determine what's a valid Path

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#69]
This is just a rough idea and I'm not sure if it's any good. Thoughts and comments are very welcome!

As we use `System.FilePath.isValid` in the parsing functions, our semantics aren't uniquely determined by the `path` version but also depend on the installed version of `filepath`. I'd like `Path` to be a less leaky abstraction.

So I'm thinking about "inlining" the `System.FilePath.isValid` function from the latest version of `filepath` in `path`. This should also allow us to prevent redundant checks and overall give us better control over performance.

We'd then have to track updates to `System.FilePath.isValid` so we can adopt bug fixes etc.

What we'd lose is the close correspondence between valid `Path`s and valid `FilePath`s. I'm not sure about  the consequences of that but we should probably investigate them pretty well before making a change.

**Comment by chrisdone** [comment]
I'm in favor. Using file path was just to avoid work, but your version dep
argument makes sense.

**Comment by sjakobi** [comment]
@mrkkrp, are you aware of any functions in path-io that will run into problems when used on a valid `Path` that happens not to be a valid `FilePath` in the sense of `System.FilePath.isValid`?

**Comment by mrkkrp** [comment]
No problems I know of.

**Comment by sjakobi** [comment]
I'm somewhat less enthusiastic about this idea now that I've seen how complex handling paths on Windows is.

In any case I'd recommend that we address #63 first and contribute optimizations back to filepath. This way we should be able to keep our FilePath-handling functions closer to their respective filepath versions and get additional sanity checking from Neil Mitchell.
