### ISSUE TITLE
Fix validity-test testsuite on Windows

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#74]
It appears that our `GenValid` instances need some optimizations to prevent the testsuite from timing out on AppVeyor.

It might be helpful to look at [System.FilePath.isValid](https://github.com/haskell/filepath/blob/master/System/FilePath/Internal.hs#L913) for some hints.

**Comment by sjakobi** [comment]
After speeding up the path generation a bit I found some first test failures:

In https://ci.appveyor.com/project/chrisdone/path/build/1.0.101:

```
Failures:

  test\ValidityTest.hs:128: 
  1) Operations: (</>) produces a valid path on when creating valid absolute file paths
       predicate failed on: "\\\\\DC3\\\227.\144\\#\247I\\\\Ip" (after 4 tests): 
       ("\\\\\DC3\\\227.\144\\#\247I\\","\\Ip")
  test\ValidityTest.hs:131: 

  2) Operations: (</>) produces a valid path on when creating valid absolute directory paths
       predicate failed on: "\\\\.\DLE:\\-\\\\" (after 7 tests): 
       ("\\\\.\DLE:\\-\\","\\")
  test\ValidityTest.hs:134: 

  3) Operations: (</>) produces a valid path on when creating valid relative file paths
       predicate failed on: "b\\\\Ip" (after 4 tests): 
       ("b\\","\\Ip")
  test\ValidityTest.hs:137: 

  4) Operations: (</>) produces a valid path on when creating valid relative directory paths
       predicate failed on: "\\\\" (after 2 tests): 
       ("\\","\\")
  test\ValidityTest.hs:47: 

  5) Operations: filename filename ($(mkRelDir parent) </> $(mkRelFile filename)) == filename $(mkRelFile filename)
       Falsifiable (after 9 tests): 
       expected: "V.\156\240."
        but got: ""
       "\\"
       "\\V.\156\240."
  test\ValidityTest.hs:52: 

  6) Operations: filename produces a valid path on when passed a valid absolute path
       predicate failed on: "" (after 1 test): 
       "\\\\li?"

Randomized with seed 864963313

Finished in 947.7440 seconds
```

**Comment by sjakobi** [comment]
To me it looks like the test failures above boil down to only a few basic problems:

1. Combining "\\" and "\\" results in an invalid path "\\\\" whose normalised version is "\\". That seems to cause failures 1-4 directly and failure 5 indirectly. This looks like a bug in our `</>`.

2. In failure 5 we inadvertedly construct an absolute directory instead of relative path to a file. That should be fixed in the same way as 1\.

3. Failure 6 looks like [this weirdness](https://github.com/haskell/filepath/blob/141cddb606fd6f6a60f730fed3d57502b93c14ae/System/FilePath/Internal.hs#L682-L689). Not sure if this can even be a file. In any case, there is no filename that can be split off.

Note that `filepath` calls `</>` "combine" and not "append". Combining filepaths seems to work in much stranger ways than I would have thought.

**Comment by sjakobi** [comment]
Oh BTW, is anyone of the maintainers here a Windows native who might have an easier time navigating these issues!?

I'm running Linux-only right now and while I can (amazingly!) use `System.FilePath.Windows` there, I can't easily reproduce the Windows behavior of `path`.

**Comment by rkoeninger** [comment]
@sjakobi  As the rare Windows Haskell user, I can take a look at this.

**Comment by sjakobi** [comment]
@rkoeninger: Thanks, please do! :+1:
