### ISSUE TITLE
Add shrinking to validity-test testsuite

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#75]
At https://github.com/commercialhaskell/path/commit/467906da26eaf850abf561c881e8043d2b64f139 I can produce a test failure with

    stack test :validity-test --test-arguments "--seed=173166278 --match Parsing"

It's hard to find the problem in the failing test case though:

```
  test/ValidityTest.hs:149: 
  1) Parsing: Path Rel Dir Produces valid paths when it succeeds
       predicate failed on: "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_/" (after 81 tests): 
       "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_"

  test/ValidityTest.hs:161: 
  2) Parsing: Path Rel File Produces valid paths when it succeeds
       predicate failed on: "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_" (after 81 tests): 
       "\161::/OW\"u@-\ENQ%\DC19<\EM\nXge\v\216\CANi'D\bmlD+(\GS\CAN\DC2\212m\128\b\241a..\186Q~<?lL7Q`IvLWsOE\n\174zxVu\174\fl\EOT8%\191\185y*_"
```

(`Path.Gen.isValid` doesn't like the `..` in the path)

This should be easier if the relevant `Arbitrary` instances had an implementation for `shrink`.

I'm not sure where to find (or to add) the relevant `Arbitrary` instances though.

@NorfairKing Could you look into this?

**Comment by NorfairKing** [comment]
I don't think `genvalidity-hspec` uses shrinking because it doesn't require an `Arbitrary` instance.

**Comment by sjakobi** [comment]
It's not based on QuickCheck?

**Comment by NorfairKing** [comment]
It's based on hspec. I'm not sure how hspec does things under the hood. Would have to look into it.

**Comment by NorfairKing** [comment]
Aha, found it:
https://hackage.haskell.org/package/QuickCheck-2.9.2/docs/Test-QuickCheck-Property.html#v:forAllShrink

We just need to replace `forAll` with `forAllShrink shrink`

**Comment by sjakobi** [comment]
> Aha, found it:
> https://hackage.haskell.org/package/QuickCheck-2.9.2/docs/Test-QuickCheck-Property.html#v:forAllShrink

Nice! I'm wondering though if shrinking should be built into `genvalidity` so you don't have to take care of it manually. (I don't mind adding it manually first though!)

**Comment by NorfairKing** [comment]
> Nice! I'm wondering though if shrinking should be built into genvalidity so you don't have to take care of it manually. (I don't mind adding it manually first though!)

That could work, but I'd need to add `shrinkValid` and `shrinkInvalid` and `shrinkUnchecked` to `GenValid`, `GenInvalid` and `GenUnchecked` respectively.

**Comment by sjakobi** [comment]
I overlooked that #84 did not add shrinking for all tests, in particular not for some of those that currently fail on Windows.

**Comment by NorfairKing** [comment]
LGTM.

**Comment by sjakobi** [comment]
I have started to work on this on [this branch](https://github.com/commercialhaskell/path/tree/75-shrink-all-the-tests) but some of the changes have made validity-test on Windows so slow that it times out on AppVeyor.

So it seems that we'll either have to do #82 first (which I currently regard as blocked by #90) or someone will have to look into this on a Windows machine. I'm not sure if I can do this soon.

In any case I've also discovered and partially fixed some test cases that didn't give as much test coverage as they should. That should be addressed no matter how this issue goes forward.

**Comment by sjakobi** [comment]
Hm, on second thought, maybe the timing out on AppVeyor isn't that bad. After all that test suite also triggers some failures Windows so we don't run it anyway. I'll try to make a PR and we can take care of the performance issues once #82 is done.

**Comment by NorfairKing** [comment]
Done in recent changes.
