### ISSUE TITLE
validity-test: Generate more "interesting" Paths

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#77]
One cause for the flaky behavior of validity-test as experienced e.g. in https://github.com/commercialhaskell/path/issues/37 seems to be that the generators don't produce enough "interesting" cases. Here's a sample:

```
λ> sample (genValid :: Gen (Path Rel Dir))
"uR@O\197r/"
"4\224;nf]/"
"j*:/"
"\245\DC1\143\DLE6#\210\212uF\154\175\ENQ\CAN\169j\202GA71~\CAN\245\&1~\SO*\147/"
"L\DLE\151\f\192[s/"
"\EM\EOT\143@\SIn/"
"\v,b\SYN*\bS\US<\GSx\222\CAN\219Z\181\b/"
"&/"
"1|P\SI3[}\169~\RS/"
"\SOH\218o*9\t\v/"
"B\f\151\DEL\166\&9@HK\\y\156\n<\222\214\t\210\b\CAN\DLE}\150DE\EOT/"
```

To the naked eye it looks like none of these paths contains multiple directories and none of these contains a dot (`.`) or even `..`.

To remediate this, I'd suggest that the generators simply increase the share of `.`, `\` and `/` characters in the generated paths. If that isn't sufficient, we could also add a list of interesting paths like `.`, `..`, `x..` etc which the generators can choose from.

**Comment by chrisdone** [comment]
Quickcheck has the `frequency` combinator with which we could choose how often we pick . \ / vs random unicode.
