### ISSUE TITLE
Travis: Compilation error doesn't cause Cabal job to fail

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#92]
https://travis-ci.org/commercialhaskell/path/jobs/216489533

I haven't investigated yet.

**Comment by sjakobi** [comment]
Here's the command we execute:

```
cabal configure --enable-tests -v2 && cabal build && cabal test --show-details=always && cabal sdist && cabal haddock | grep "100%" | wc -l | grep "2"
```

Looks like the piping shadows the non-zero exit status of the input commands

```
$ false
$ echo $?
1
$ false | cat
$ echo $?
0
```

@mrkkrp Do you mind if I simply remove the Haddock coverage check or are you aware of a better solution?

**Comment by NorfairKing** [comment]
Why ont use multiple commands below each other?

**Comment by sjakobi** [comment]
Even then we wouldn't see a failure if the Haddocks were broken.

I guess we could do something like

```
stack haddock
stack clean
stack haddock | check-coverage
```

**Comment by NorfairKing** [comment]
> Even then we wouldn't see a failure if the Haddocks were broken.

That's true. You could try saving the output of `stack` haddock to a tmp file and check the exit code before you run check-coverage on that file

**Comment by mrkkrp** [comment]
> Even then we wouldn't see a failure if the Haddocks were broken.

I'm not sure, I'm using this everywhere, works as expected.

Here is how:

https://github.com/mrkkrp/megaparsec/blob/master/.travis.yml#L34

If coverage is not 100%, I get failure, otherwise everything is green.

**Comment by sjakobi** [comment]
I guess when the haddocks are malformatted the coverage output is missing which causes the subsequent commands to fail.

**Comment by mrkkrp** [comment]
That's the desired behavior, no? I want to know about malformed Haddocks.

**Comment by sjakobi** [comment]
Sure, the original error is silenced but the coverage check still causes the command to fail. That's ok as far as I am concerned.

**Comment by mrkkrp** [comment]
So we need to separate the commands instead of chaining them with `&&` and the problem should be solved.
