### ISSUE TITLE
Rename isParentOf to isPrefixOf

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/path#93]
As discussed in #90, `isParentOf` is a misnomer, leading to confusion at times. `isPrefixOf` conveys the meaning more clearly and effectively. We could rename the API and deprecate the old name.

**Comment by NorfairKing** [comment]
`isPrefixOf` clashes with `Data.List.isPrefixOf`.
I prefer `isAncestorOf`.

**Comment by harendra-kumar** [comment]
> Deprecate the current function and add the new one.

Yes, that's what I meant.

I did not realize the clash. `isAncestorOf` is fine then.

**Comment by sjakobi** [comment]
:+1: for `isAncestorOf`.

**Comment by harendra-kumar** [comment]
I am going with `isDirPrefixOf` and also renaming `stripDir` to `stripDirPrefix`. That makes both these API names consistent with each other and also conveys the meaning precisely without confusion in case of relative paths as well as absolute paths. Also since the name says prefix rather than parent making it clear that `isDirPrefixOf "/" "/"` and `isDirPrefixOf "." "."` return false.

**Comment by NorfairKing** [comment]
No. `a/b/c` is a prefix of `a/b/c` `"/"` is a prefix of `"/"`. If you want to use the word "prefix", then you need to use "strictPrefix".

**Comment by harendra-kumar** [comment]
`Proper prefix` is the correct technical jargon. `isProperPrefixOf` and `stripProperPrefix` are more accurate but make the names longer, might still work though.

To rethink the behavior of the APIs themselves, I am also not sure if `proper prefix` versions are the more useful APIs or we should instead have APIs with `prefix` behavior and name them so?

**Comment by NorfairKing** [comment]
If you want to go for renaming (not implementing something else), then I suggest correctly naming the current semantics. I'm not sure which one would be more useful though.

**Comment by harendra-kumar** [comment]
Ok, renamed to `proper prefix`. please take a look at the PR.
