### ISSUE TITLE
Introduce a polymorphic basename API

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/path#94]
We can use a polymorphic API to represent the basename of a dir or a file uniformly, simplifying the API and making it the same as POSIX, which is a bonus and helpful for people used to the POSIX APIs:

```haskell
class HasBasename b where
    basename :: Path b t -> Path Rel t

instance HasBasename Abs where
    basename (Path fp) | FilePath.isDrive fp = Path []
    basename (Path l) = Path (last (FilePath.splitPath l))

instance HasBasename Rel where
    basename p@(Path []) = p
    basename (Path l) = Path (last (FilePath.splitPath l))

filename :: HasBasename b => Path b File -> Path Rel File
filename  = basename

dirname :: HasBasename b => Path b Dir -> Path Rel Dir
dirname = basename
```

If we deprecate the old `filename` and `dirname` APIs, it will also remove the confusion caused by the difference in `dirname` semantics of the path package and POSIX.

**Comment by NorfairKing** [comment]
I'm undecided on whether I like this, but this is a good place to discuss it.

**Comment by harendra-kumar** [comment]
Referencing the original discussion https://github.com/commercialhaskell/path/pull/90#issuecomment-291730229.

**Comment by harendra-kumar** [comment]
@NorfairKing, as I thought more about it, I am sort of swaying towards your earlier stand on this. Since the type always expresses `File` or `Dir`, its okay to have `fileName` and `dirName` as separate APIs and the names are consistent with the types which I like. The only thing is conflict with POSIX but that is not a primary consideration, we get used to it and types anyway protect us. Symmetry and consistency of APIs within the package is primary.

**Comment by harendra-kumar** [comment]
On the other hand, what is the downside of having `basename`?

**Comment by NorfairKing** [comment]
As I said: 

* Error messages, now you'll get 'no instance of WhateverClassWeUseversusit is not a File`
* Ambiguities: Type classes can counteract type inference in some cases.
* Unnecessary complexity (in this case) because you mostly either deal with a file or a path, not both.

**Comment by harendra-kumar** [comment]
This does not give us much other than POSIX compatibility. Closing it.
